Add python coding standards to doc
gchq/gaffer-doc pull request #316
Opened 2022-10-18 12:22 UTC by lb324567

Update docs with guidance on the Python coding standards we are enforcing.

2022-10-18 13:18 UTC, GCHQDeveloper314 approved these changes

2022-10-18 16:00 UTC, t92549 requested changes

2022-10-18 16:00 UTC, t92549 commented on docs/ways-of-working.md
> +* Module level imports at the top of the file -  this will not be enforce but is recommended where it does not cause issues with the code generated by Fishbowl.
There is one extra space after  `-  `,  and should be `enforced`

2022-10-18 16:00 UTC, t92549 commented on docs/ways-of-working.md
> +`autopep8 --exit-code --r --i --a --a --max-line-length 100 --ignore E402 .`
These should only have one dash, see the [pipeline](https://github.com/gchq/gaffer-tools/blob/2af6914e65a6987b0a32a61a3d27ed52917c0836/.github/workflows/continuous-integration.yaml#L21)

2022-10-20 09:05 UTC, t92549 approved these changes

2022-10-20 09:12 UTC, merged