Gh-471: Add page explaining visibilities
gchq/gaffer-doc pull request #494
Opened 2024-05-30 08:35 UTC by wb36499

- Replicates v1 docs visibilities page in new formatting
- Replaces link to v1 docs guide with new page

2024-05-30 10:33 UTC, GCHQDeveloper314 requested changes

2024-05-30 10:33 UTC, GCHQDeveloper314 commented on docs/administration-guide/security/security-guide.md
> +We've defined a new "visibility" type in our Types, which is a Java String and must be non-null in order for the related edge to be loaded into the Graph. We also specified that the visibility proper
This line is too long

2024-05-30 10:33 UTC, GCHQDeveloper314 commented on docs/administration-guide/security/security-guide.md
> +The code for this example is [Visibilities](https://github.com/gchq/gaffer-doc/blob/v1docs/src/main/java/uk/gov/gchq/gaffer/doc/dev/walkthrough/Visibilities.java)
Previously these links to the old docs example code have not been included in the new docs.

2024-05-30 13:25 UTC, tb06904 commented on docs/administration-guide/security/security-guide.md
> +The code for this example is [Visibilities](https://github.com/gchq/gaffer-doc/blob/v1docs/src/main/java/uk/gov/gchq/gaffer/doc/dev/walkthrough/Visibilities.java)
Yeah this can probably just be a link to the Javadocs of the `Visibilities` class.

2024-05-30 13:25 UTC, tb06904 commented on docs/administration-guide/security/security-guide.md
> +We've defined a new "visibility" type in our Types, which is a Java String and must be non-null in order for the related edge to be loaded into the Graph. We also specified that the visibility proper
The links need changing here to the javadocs ideally for each class. Also to reiterate @GCHQDeveloper314 's comment you can probably just bulk format to line wrap at a char limit (usually 80 or 100)

2024-05-30 13:25 UTC, tb06904 commented on docs/administration-guide/security/security-guide.md
> +We have updated the generator to add the visibility label as a new property (a Java String) on the edges:
This isn't really very relevant for the v2 docs as it does not talk through the element generator like the v1 docs did. You would be better showing how you can generically add an element with the visibility property

2024-06-06 09:28 UTC, GCHQDeveloper314 approved these changes

2024-06-06 09:38 UTC, cn337131 approved these changes

2024-06-06 13:04 UTC, merged